### ISSUE TITLE
大佬 方便留个联系方式么 模块部署好了怎么操作

### ISSUE THREAD

**Issue by saosaosaosao** [whitespacename/RE2AC#1]

**Comment by whitespacename** [comment]
还没适配模拟器，等我周末抽空看看

**Comment by whitespacename** [comment]
测试完成
![1](https://user-images.githubusercontent.com/117577679/204125263-581b0f01-40d3-4ebc-8768-1a1ca66a7e40.jpg)
模拟器上会显示兼容问题，不用管无视就好
![2](https://user-images.githubusercontent.com/117577679/204125274-991161be-2e45-4307-bc10-a8486703959d.jpg)
