### ISSUE TITLE
模拟器存在兼容性问题啊

### ISSUE THREAD

**Issue by IIIIIriss** [whitespacename/RE2AC#2]
是模拟器的原因吗
![QQ图片20221210220830](https://user-images.githubusercontent.com/120243836/206859402-475b0245-fa52-4f85-9371-5edaf9c53237.png)

**Comment by whitespacename** [comment]
正常，我测试过
https://github.com/whitespacename/RE2AC/issues/1#issuecomment-1328192653

**Comment by whitespacename** [comment]
还有你下载错了吧，模拟器版的版本号到`F`了
