### ISSUE TITLE
大佬，第一次搞，为啥装好没反应啊

### ISSUE THREAD

**Issue by abai126** [whitespacename/RE2AC#3]

**Comment by abai126** [comment]
[](url)
![Screenshot_2023-02-04-03-52-13-046_com topjohnwu](https://user-images.githubusercontent.com/124397638/216697416-20ff5832-8a36-4e3e-ae6d-429ca960cfd4.jpg)
这样是装好了吗

**Comment by whitespacename** [comment]
是啊，你可以用logcat看看日志
用终端模拟器一行一个回车
su
logcat -s RE2AC:V

**Comment by abai126** [comment]
好的，我还有仨小时下班，这个东西装在我的备用机上的，等我下班回家看一下

**Comment by abai126** [comment]
![1675831438548](https://user-images.githubusercontent.com/124397638/217435784-ba2353a3-b294-4672-a6b8-1ae257c8ede3.jpg)
大佬是这样吗

**Comment by abai126** [comment]
![1675831438548](https://user-images.githubusercontent.com/124397638/217435919-46feaeec-d036-4214-bf2d-76d1e068757e.jpg)

**Comment by whitespacename** [comment]
忘了说，你得保持这个界面然后打开游戏再看看有没有显示什么

**Comment by abai126** [comment]
维护刚结束，是这样吗
![1675926539642](https://user-images.githubusercontent.com/124397638/217742607-ec2c8c78-f5ed-46d9-a5f5-576e3016d66d.jpg)

**Comment by whitespacename** [comment]
看样子是比较旧的Android版本了，把`/system/bin/linker`和`/system/bin/linker64(如果有)`发给我适配一下
可以下载一个re管理器然后找这两个文件

**Comment by qihang0000000** [comment]
作者你好，可以问一下这个模块实现反和谐的原理吗？com.sunborn.girlsfrontline.cn这个包需要在哪里下载呢？

**Comment by abai126** [comment]
https://pan.baidu.com/s/137Bymox4N53dpY6TIbroig?pwd=9x5k     密码是9x5k，大佬这个回复好像不能附带文件，我给上传到网盘了，我这两个文件都有

**Comment by whitespacename** [comment]
好了，下载最新的`F`版试试

**Comment by abai126** [comment]
![1676092189600](https://user-images.githubusercontent.com/124397638/218241427-65d04a30-0e61-424a-b222-9cc70c9bf607.jpg)
![1676092189600](https://user-images.githubusercontent.com/124397638/218241430-7235889c-5e70-4b6b-a5d3-4955df9632d4.jpg)

这回直接装不上了大佬，我试了一下还是没用

**Comment by abai126** [comment]
![1676092213843](https://user-images.githubusercontent.com/124397638/218241532-0090b416-7cb9-48d8-b164-d4ae3f7a2b52.jpg)
这个是打开游戏的样子

**Comment by whitespacename** [comment]
更新了，忘了还有这茬

**Comment by abai126** [comment]
装上了大佬，但是游戏还是原版，还是没有反和谐
下面是那个终端的

WARNING: linker: /data/app/com.termoneplus-1/lib/arm64/libexec-t1plus.so: unsupported flags DT_FLAGS_1=0x8000001
oxygen:/ $ su
WARNING: linker: /data/app/com.termoneplus-1/lib/arm64/libexec-t1plus.so: unsupported flags DT_FLAGS_1=0x8000001
1|oxygen:/ # logact -s RE2AC:V
/system/bin/sh: logact: not found
127|oxygen:/ # logcat -s.RE2AC:V
Unrecognized Option .
Usage: logcat [options] [filterspecs]
options include:
  -s              Set default filter to silent. Equivalent to filterspec '*:S'
  -f <file>, --file=<file>               Log to file. Default is stdout
  -r <kbytes>, --rotate-kbytes=<kbytes>
                  Rotate log every kbytes. Requires -f option
  -n <count>, --rotate-count=<count>
                  Sets max number of rotated logs to <count>, default 4
  -v <format>, --format=<format>
                  Sets the log print format, where <format> is:
                    brief color epoch long monotonic printable process raw
                    tag thread threadtime time uid usec UTC year zone
  -D, --dividers  Print dividers between each log buffer
  -c, --clear     Clear (flush) the entire log and exit
                  if Log to File specified, clear fileset instead
  -d              Dump the log and then exit (don't block)
  -e <expr>, --regex=<expr>
                  Only print lines where the log message matches <expr>
                  where <expr> is a regular expression
  -m <count>, --max-count=<count>
                  Quit after printing <count> lines. This is meant to be
                  paired with --regex, but will work on its own.
  --print         Paired with --regex and --max-count to let content bypass
                  regex filter but still stop at number of matches.  -t <count>      Print only the most recent <count> lines (implies -d)
  -t '<time>'     Print most recent lines since specified time (implies -d)
  -T <count>      Print only the most recent <count> lines (does not imply -d)
  -T '<time>'     Print most recent lines since specified time (not imply -d)
                  count is pure numerical, time is 'MM-DD hh:mm:ss.mmm...'
                  'YYYY-MM-DD hh:mm:ss.mmm...' or 'sssss.mmm...' format
  -g, --buffer-size                      Get the size of the ring buffer.
  -G <size>, --buffer-size=<size>
                  Set size of log ring buffer, may suffix with K or M.
  -L, -last       Dump logs from prior to last reboot
  -b <buffer>, --buffer=<buffer>         Request alternate ring buffer, 'main',
                  'system', 'radio', 'events', 'crash', 'default' or 'all'.
                  Multiple -b parameters or comma separated list of buffers are
                  allowed. Buffers interleaved. Default -b main,system,crash.
  -B, --binary    Output the log in binary.
  -S, --statistics                       Output statistics.
  -p, --prune     Print prune white and ~black list. Service is specified as
                  UID, UID/PID or /PID. Weighed for quicker pruning if prefix
                  with ~, otherwise weighed for longevity if unadorned. All
                  other pruning activity is oldest first. Special case ~!
                  represents an automatic quicker pruning for the noisiest
                  UID as determined by the current statistics.
  -P '<list> ...', --prune='<list> ...'
                  Set prune white and ~black list, using same format as
                  listed above. Must be quoted.
  --pid=<pid>     Only prints logs from the given pid.
  --wrap          Sleep for 2 hours or when buffer about to wrap whichever
                  comes first. Improves efficiency of polling by providing
                  an about-to-wrap wakeup.

filterspecs are a series of
  <tag>[:priority]

where <tag> is a log component tag (or * for all) and priority is:
  V    Verbose (default for <tag>)
  D    Debug (default for '*')
  I    Info
  W    Warn
  E    Error
  F    Fatal
  S    Silent (suppress all output)

'*' by itself means '*:D' and <tag> by itself means <tag>:V.
If no '*' filterspec or -s on command line, all filter defaults to '*:V'.
eg: '*:S <tag>' prints only <tag>, '<tag>:S' suppresses all <tag> log messages.

If not specified on the command line, filterspec is set from ANDROID_LOG_TAGS.

If not specified with -v on command line, format is set from ANDROID_PRINTF_LOG
or defaults to "threadtime"

1|oxygen:/ #

**Comment by abai126** [comment]
刚才是打错指令了，现在是这样，还是没反应

**Comment by abai126** [comment]
![Uploading Screenshot_2023-02-11-14-22-27-941_com.sunborn.girlsfrontline.cn.jpg…]()

**Comment by abai126** [comment]
![1675926539642](https://user-images.githubusercontent.com/124397638/218244228-0bf50ddc-f819-467d-91aa-99c5aadfbb70.jpg)

**Comment by abai126** [comment]
跟这张一样但是最后一行也没了，新的我传不上来了

**Comment by whitespacename** [comment]
更新了一下依赖库，你再试试？

**Comment by whitespacename** [comment]
还有上传图片要等Uploading转圈结束再点击Comment

**Comment by abai126** [comment]
![Screenshot_2023-02-11-15-14-05-000_com sunborn girlsfrontline cn](https://user-images.githubusercontent.com/124397638/218245942-3c22f871-5903-4909-9612-210cbceb2877.jpg)

**Comment by abai126** [comment]
还是不行

**Comment by whitespacename** [comment]
草，原来问题在这里，你这是andorid几啊

**Comment by abai126** [comment]
大佬，是7.1.1

**Comment by whitespacename** [comment]
更新了，这次应该可以了

**Comment by abai126** [comment]
![1676110518696](https://user-images.githubusercontent.com/124397638/218252635-f87f705c-d648-432f-a413-614c5b51922b.jpg)
这回行了，谢谢大佬
