### ISSUE TITLE
大佬请教一下，本人手机红米K50pro，安卓版本13，装了模块之后显示正常运行，但是终端没有日志

### ISSUE THREAD

**Issue by AsakawaAkane** [whitespacename/RE2AC#5]
![Screenshot_2023-03-11-01-18-47-637_com topjohnwu magisk](https://user-images.githubusercontent.com/53263244/224382848-178226b6-ea9c-4339-a102-1d7c1ada6094.jpg)
![Screenshot_2023-03-11-01-19-26-052_com termux](https://user-images.githubusercontent.com/53263244/224382854-9ce4b640-71fd-4a30-9f58-4f07d90ca134.jpg)
另外我的少前是B服的，包名是com.digitalsky.girlsfrontline.cn.bili，不知道能不能使用该模块，请大佬指教一下，感谢！

**Comment by whitespacename** [comment]
理论上可以，我加上包名你更新一下模块试试

**Comment by AsakawaAkane** [comment]
还是不行，magisk里模块的状态是启用的，但是日志始终没有beginning相关的回显。
Zygisk也是正常运行的。

**Comment by whitespacename** [comment]
把/system/linker和/system/liner64发给我看看先

**Comment by AsakawaAkane** [comment]
[linker+linker64.zip](https://github.com/whitespacename/RE2AC/files/10953623/linker%2Blinker64.zip)
OK

**Comment by whitespacename** [comment]
更新了

**Comment by AsakawaAkane** [comment]
![QQ图片20230314234913](https://user-images.githubusercontent.com/53263244/225058372-8ae9d9ee-8b87-4d55-88e1-1e8dff6aabac.jpg)
![QQ图片20230314234918](https://user-images.githubusercontent.com/53263244/225058397-92150613-c0a4-4105-ba2e-4ff28240a59b.jpg)
成功了！感谢！

**Comment by AsakawaAkane** [comment]
![QQ图片20230314234913](https://user-images.githubusercontent.com/53263244/225058488-3f23cb8a-5c86-4ef3-ae26-b9f187b822b3.jpg)

**Comment by ASD106053468ASD** [comment]
你好，请问我的雷电9 64位安卓9  为啥装了模块之后b服闪退
