### ISSUE TITLE
大佬 现在雷电9  官服更新了之后也会闪退了  

### ISSUE THREAD

**Issue by saosaosaosao** [whitespacename/RE2AC#8]
官方的包难道检测root了？

**Comment by ASD106053468ASD** [comment]
我b服没法用虚拟机了

**Comment by saosaosaosao** [comment]
看了下  游戏本身不检测root  是运行zygisk_RE2AC模块会直接闪退

**Comment by ASD106053468ASD** [comment]
有什么解决办法吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月23日(周日) 中午11:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [whitespacename/RE2AC] 大佬 现在雷电9  官服更新了之后也会闪退了   (Issue #8)




 
看了下  游戏本身不检测root  是运行zygisk_RE2AC模块会直接闪退

**Comment by saosaosaosao** [comment]
无

**Comment by ASD106053468ASD** [comment]
你会替换文件反和谐吗

**Comment by saosaosaosao** [comment]
替换台服的catch_data吗 那个治标不治本 只能开启大破  原皮肤还是被和谐的      暴力替换立绘行不通 会被检测重新下载

**Comment by whitespacename** [comment]
最近都没登游戏，不过我这边没问题

![Snipaste_2023-05-04_18-32-53](https://user-images.githubusercontent.com/117577679/236180036-fd763208-979d-4b7f-bc3f-86294b8ef0ce.jpg)

版本号是`3.0200_415`，安装的是`x86`架构文件，可以在`/data/app/com.sunborn.girlsfrontline.cn-xxxxxxxxxx/lib`文件夹下看看

**Comment by saosaosaosao** [comment]
大佬雷电模拟器版本是啥

**Comment by ASD106053468ASD** [comment]
我的b服是不是也是因为模拟器版本不行

**Comment by ASD106053468ASD** [comment]
现在的版本是542不是415

**Comment by mubaiaerdan** [comment]
官网下载的3.0200_415在/data/app/com.sunborn.girlsfrontline.cn-xxxxxxxxxx/lib下显示的是arm，这个应该是64位？老版本的安装包显示的x86，怪不得打不开orz。

**Comment by saosaosaosao** [comment]
有解决办法么 

> 官网下载的3.0200_415在/data/app/com.sunborn.girlsfrontline.cn-xxxxxxxxxx/lib下显示的是arm，这个应该是64位？老版本的安装包显示的x86，怪不得打不开orz。

有解决办法吗

**Comment by mubaiaerdan** [comment]
> 有解决办法么
> 
> > 官网下载的3.0200_415在/data/app/com.sunborn.girlsfrontline.cn-xxxxxxxxxx/lib下显示的是arm，这个应该是64位？老版本的安装包显示的x86，怪不得打不开orz。
> 
> 有解决办法吗
没有orz

**Comment by ASD106053468ASD** [comment]
B服咋办

**Comment by whitespacename** [comment]
小问题，教你们怎么用adb重新覆盖安装，adb在模拟器的安装目录中找，应该和`dnplayer.exe`放在一起
然后在adb所在的文件夹空白处按住shitf键点击鼠标右键从`cmd`或者`powershell`打开
如果是从powershell打开的话，`adb install`要改成`.\adb install`

首先如果你的电脑上有下载好的安装包，那就
`adb install -r --abi x86 D:\Download\xxxxx.apk`
把`D:\Download\xxxxx.apk`换成安装包的位置

如果没有的话，也可以直接在模拟器中覆盖，不过比较麻烦
首先输入`adb shell`
然后输入`pm list packages -f |grep sunborn`
然后复制apk的路径，比如`/data/app/com.sunborn.girlsfrontline.cn-Ixwh8Oen0PQUnYzV_BQ9bA==/base.apk`
最后，`pm install -r --abi x86 /data/app/com.sunborn.girlsfrontline.cn-Ixwh8Oen0PQUnYzV_BQ9bA==/base.apk`
出现`Success`之后结束
![Snipaste_2023-05-05_18-30-09](https://user-images.githubusercontent.com/117577679/236435733-1521301d-5831-49c3-a1a4-80a9e1f68edf.jpg)

至于为什么arm64会闪退，是因为距离上次安装包中出现arm64版本的library大概是一年前了，模块没有适配233

**Comment by ASD106053468ASD** [comment]
> 小问题，教你们怎么用adb重新覆盖安装，adb在模拟器的安装目录中找，应该和`dnplayer.exe`放在一起 然后在adb所在的文件夹空白处按住shitf键点击鼠标右键从`cmd`或者`powershell`打开 如果是从powershell打开的话，`adb install`要改成`.\adb install`
> 
> 首先如果你的电脑上有下载好的安装包，那就 `adb install -r --abi x86 D:\Download\xxxxx.apk` 把`D:\Download\xxxxx.apk`换成安装包的位置
> 
> 如果没有的话，也可以直接在模拟器中覆盖，不过比较麻烦 首先输入`adb shell` 然后输入`pm list packages -f |grep sunborn` 然后复制apk的路径，比如`/data/app/com.sunborn.girlsfrontline.cn-Ixwh8Oen0PQUnYzV_BQ9bA==/base.apk` 最后，`pm install -r --abi x86 /data/app/com.sunborn.girlsfrontline.cn-Ixwh8Oen0PQUnYzV_BQ9bA==/base.apk` 出现`Success`之后结束 ![Snipaste_2023-05-05_18-30-09](https://user-images.githubusercontent.com/117577679/236435733-1521301d-5831-49c3-a1a4-80a9e1f68edf.jpg)
> 
> 至于为什么arm64会闪退，是因为距离上次安装包中出现arm64版本的library大概是一年前了，模块没有适配233

大佬要咋适配

**Comment by mubaiaerdan** [comment]
> pm install -r --abi



> 小问题，教你们怎么用adb重新覆盖安装，adb在模拟器的安装目录中找，应该和`dnplayer.exe`放在一起 然后在adb所在的文件夹空白处按住shitf键点击鼠标右键从`cmd`或者`powershell`打开 如果是从powershell打开的话，`adb install`要改成`.\adb install`
> 
> 首先如果你的电脑上有下载好的安装包，那就 `adb install -r --abi x86 D:\Download\xxxxx.apk` 把`D:\Download\xxxxx.apk`换成安装包的位置
> 
> 如果没有的话，也可以直接在模拟器中覆盖，不过比较麻烦 首先输入`adb shell` 然后输入`pm list packages -f |grep sunborn` 然后复制apk的路径，比如`/data/app/com.sunborn.girlsfrontline.cn-Ixwh8Oen0PQUnYzV_BQ9bA==/base.apk` 最后，`pm install -r --abi x86 /data/app/com.sunborn.girlsfrontline.cn-Ixwh8Oen0PQUnYzV_BQ9bA==/base.apk` 出现`Success`之后结束 ![Snipaste_2023-05-05_18-30-09](https://user-images.githubusercontent.com/117577679/236435733-1521301d-5831-49c3-a1a4-80a9e1f68edf.jpg)
> 
> 至于为什么arm64会闪退，是因为距离上次安装包中出现arm64版本的library大概是一年前了，模块没有适配233

成功了，感谢大佬

**Comment by ASD106053468ASD** [comment]
> > pm install -r --abi
> 
> > 小问题，教你们怎么用adb重新覆盖安装，adb在模拟器的安装目录中找，应该和`dnplayer.exe`放在一起 然后在adb所在的文件夹空白处按住shitf键点击鼠标右键从`cmd`或者`powershell`打开 如果是从powershell打开的话，`adb install`要改成`.\adb install`
> > 首先如果你的电脑上有下载好的安装包，那就 `adb install -r --abi x86 D:\Download\xxxxx.apk` 把`D:\Download\xxxxx.apk`换成安装包的位置
> > 如果没有的话，也可以直接在模拟器中覆盖，不过比较麻烦 首先输入`adb shell` 然后输入`pm list packages -f |grep sunborn` 然后复制apk的路径，比如`/data/app/com.sunborn.girlsfrontline.cn-Ixwh8Oen0PQUnYzV_BQ9bA==/base.apk` 最后，`pm install -r --abi x86 /data/app/com.sunborn.girlsfrontline.cn-Ixwh8Oen0PQUnYzV_BQ9bA==/base.apk` 出现`Success`之后结束 ![Snipaste_2023-05-05_18-30-09](https://user-images.githubusercontent.com/117577679/236435733-1521301d-5831-49c3-a1a4-80a9e1f68edf.jpg)
> > 至于为什么arm64会闪退，是因为距离上次安装包中出现arm64版本的library大概是一年前了，模块没有适配233
> 
> 成功了，感谢大佬

老哥可以帮忙试一试b服的吗

**Comment by mubaiaerdan** [comment]
> > > pm install -r --abi
> > 
> > 
> > > 小问题，教你们怎么用adb重新覆盖安装，adb在模拟器的安装目录中找，应该和`dnplayer.exe`放在一起 然后在adb所在的文件夹空白处按住shitf键点击鼠标右键从`cmd`或者`powershell`打开 如果是从powershell打开的话，`adb install`要改成`.\adb install`
> > > 首先如果你的电脑上有下载好的安装包，那就 `adb install -r --abi x86 D:\Download\xxxxx.apk` 把`D:\Download\xxxxx.apk`换成安装包的位置
> > > 如果没有的话，也可以直接在模拟器中覆盖，不过比较麻烦 首先输入`adb shell` 然后输入`pm list packages -f |grep sunborn` 然后复制apk的路径，比如`/data/app/com.sunborn.girlsfrontline.cn-Ixwh8Oen0PQUnYzV_BQ9bA==/base.apk` 最后，`pm install -r --abi x86 /data/app/com.sunborn.girlsfrontline.cn-Ixwh8Oen0PQUnYzV_BQ9bA==/base.apk` 出现`Success`之后结束 ![Snipaste_2023-05-05_18-30-09](https://user-images.githubusercontent.com/117577679/236435733-1521301d-5831-49c3-a1a4-80a9e1f68edf.jpg)
> > > 至于为什么arm64会闪退，是因为距离上次安装包中出现arm64版本的library大概是一年前了，模块没有适配233
> > 
> > 
> > 成功了，感谢大佬
> 
> 老哥可以帮忙试一试b服的吗

B服也成功下载了反和谐的数据包

**Comment by ASD106053468ASD** [comment]
> 

你的雷电模拟器是啥版本的

**Comment by ASD106053468ASD** [comment]
> > > > pm install -r --abi
> > > 
> > > 
> > > > 小问题，教你们怎么用adb重新覆盖安装，adb在模拟器的安装目录中找，应该和`dnplayer.exe`放在一起 然后在adb所在的文件夹空白处按住shitf键点击鼠标右键从`cmd`或者`powershell`打开 如果是从powershell打开的话，`adb install`要改成`.\adb install`
> > > > 首先如果你的电脑上有下载好的安装包，那就 `adb install -r --abi x86 D:\Download\xxxxx.apk` 把`D:\Download\xxxxx.apk`换成安装包的位置
> > > > 如果没有的话，也可以直接在模拟器中覆盖，不过比较麻烦 首先输入`adb shell` 然后输入`pm list packages -f |grep sunborn` 然后复制apk的路径，比如`/data/app/com.sunborn.girlsfrontline.cn-Ixwh8Oen0PQUnYzV_BQ9bA==/base.apk` 最后，`pm install -r --abi x86 /data/app/com.sunborn.girlsfrontline.cn-Ixwh8Oen0PQUnYzV_BQ9bA==/base.apk` 出现`Success`之后结束 ![Snipaste_2023-05-05_18-30-09](https://user-images.githubusercontent.com/117577679/236435733-1521301d-5831-49c3-a1a4-80a9e1f68edf.jpg)
> > > > 至于为什么arm64会闪退，是因为距离上次安装包中出现arm64版本的library大概是一年前了，模块没有适配233
> > > 
> > > 
> > > 成功了，感谢大佬
> > 
> > 
> > 老哥可以帮忙试一试b服的吗
> 
> B服也成功下载了反和谐的数据包


你的雷电模拟器是啥版本的

**Comment by ASD106053468ASD** [comment]
> > > > pm install -r --abi
> > > 
> > > 
> > > > 小问题，教你们怎么用adb重新覆盖安装，adb在模拟器的安装目录中找，应该和`dnplayer.exe`放在一起 然后在adb所在的文件夹空白处按住shitf键点击鼠标右键从`cmd`或者`powershell`打开 如果是从powershell打开的话，`adb install`要改成`.\adb install`
> > > > 首先如果你的电脑上有下载好的安装包，那就 `adb install -r --abi x86 D:\Download\xxxxx.apk` 把`D:\Download\xxxxx.apk`换成安装包的位置
> > > > 如果没有的话，也可以直接在模拟器中覆盖，不过比较麻烦 首先输入`adb shell` 然后输入`pm list packages -f |grep sunborn` 然后复制apk的路径，比如`/data/app/com.sunborn.girlsfrontline.cn-Ixwh8Oen0PQUnYzV_BQ9bA==/base.apk` 最后，`pm install -r --abi x86 /data/app/com.sunborn.girlsfrontline.cn-Ixwh8Oen0PQUnYzV_BQ9bA==/base.apk` 出现`Success`之后结束 ![Snipaste_2023-05-05_18-30-09](https://user-images.githubusercontent.com/117577679/236435733-1521301d-5831-49c3-a1a4-80a9e1f68edf.jpg)
> > > > 至于为什么arm64会闪退，是因为距离上次安装包中出现arm64版本的library大概是一年前了，模块没有适配233
> > > 
> > > 
> > > 成功了，感谢大佬
> > 
> > 
> > 老哥可以帮忙试一试b服的吗
> 
> B服也成功下载了反和谐的数据包


你的雷电模拟器是啥版本的

**Comment by mubaiaerdan** [comment]
> > > > > pm install -r --abi
> > > > 
> > > > 
> > > > > 小问题，教你们怎么用adb重新覆盖安装，adb在模拟器的安装目录中找，应该和`dnplayer.exe`放在一起 然后在adb所在的文件夹空白处按住shitf键点击鼠标右键从`cmd`或者`powershell`打开 如果是从powershell打开的话，`adb install`要改成`.\adb install`
> > > > > 首先如果你的电脑上有下载好的安装包，那就 `adb install -r --abi x86 D:\Download\xxxxx.apk` 把`D:\Download\xxxxx.apk`换成安装包的位置
> > > > > 如果没有的话，也可以直接在模拟器中覆盖，不过比较麻烦 首先输入`adb shell` 然后输入`pm list packages -f |grep sunborn` 然后复制apk的路径，比如`/data/app/com.sunborn.girlsfrontline.cn-Ixwh8Oen0PQUnYzV_BQ9bA==/base.apk` 最后，`pm install -r --abi x86 /data/app/com.sunborn.girlsfrontline.cn-Ixwh8Oen0PQUnYzV_BQ9bA==/base.apk` 出现`Success`之后结束 ![Snipaste_2023-05-05_18-30-09](https://user-images.githubusercontent.com/117577679/236435733-1521301d-5831-49c3-a1a4-80a9e1f68edf.jpg)
> > > > > 至于为什么arm64会闪退，是因为距离上次安装包中出现arm64版本的library大概是一年前了，模块没有适配233
> > > > 
> > > > 
> > > > 成功了，感谢大佬
> > > 
> > > 
> > > 老哥可以帮忙试一试b服的吗
> > 
> > 
> > B服也成功下载了反和谐的数据包
> 
> 你的雷电模拟器是啥版本的

我的是9.0.19

**Comment by ASD106053468ASD** [comment]
大佬强啊，成功了

**Comment by Logikn** [comment]
大佬，载入一直转圈圈怎么办
